
import { GoogleGenerativeAI } from "@google/generative-ai";

export default async function handler(req, res) {
    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    try {
        const apiKey = process.env.GOOGLE_GEMINI_API_KEY;
        if (!apiKey) {
            console.error('Server: Missing API Key');
            throw new Error('Configuration Error');
        }

        const { prompt, imageBase64 } = req.body;

        // --- SECURITY VALIDATION ---
        if (!prompt || typeof prompt !== 'string') {
            return res.status(400).json({ error: 'Invalid Prompt' });
        }

        if (prompt.length > 5000) {
            return res.status(400).json({ error: 'Prompt too long (Max 500 chars)' });
        }

        if (imageBase64) {
            // Approx check for crazy large payloads
            if (imageBase64.length > 15 * 1024 * 1024) { // ~11MB limit
                return res.status(413).json({ error: 'Reference Image too large' });
            }
        }
        // --- END VALIDATION ---

        // Reverting to Imagen 3.0 as 4.0 does not reliably support Image-to-Image on this endpoint
        let currentUrl = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${apiKey}`;

        let currentRequestBody = {
            instances: [
                {
                    prompt: `Photorealistic industrial safety visualization, high quality, 4k: ${prompt}`,
                    image: imageBase64 ? { bytesBase64Encoded: imageBase64 } : undefined
                }
            ],
            parameters: {
                sampleCount: 1,
                aspectRatio: "4:3"
            }
        };

        const makeRequest = async (url, body) => {
            const res = await fetch(url, {
                method: 'POST',
                headers: { 'Content-Type': 'application/json' },
                body: JSON.stringify(body)
            });
            if (!res.ok) {
                const errData = await res.json();
                throw { status: res.status, data: errData };
            }
            return res.json();
        };

        let data;
        try {
            data = await makeRequest(currentUrl, currentRequestBody);
        } catch (firstError) {
            console.warn("First attempt (Image-to-Image) failed:", firstError.data?.error?.message);

            // Fallback: If error relates to "Image in input is not supported" or similar 400/404, try text-only
            if (imageBase64) {
                console.log("Retrying with Text-to-Image fallback...");
                currentRequestBody.instances[0].image = undefined; // Remove image
                // Optional: Slightly adjust prompt to be more descriptive since we lost the reference image
                currentRequestBody.instances[0].prompt = `Industrial safety scene, high quality, 4k. Context: ${prompt}`;

                try {
                    data = await makeRequest(currentUrl, currentRequestBody);
                } catch (secondError) {
                    console.error('Fallback (Text-to-Image) also failed:', secondError.data);
                    const errorMessage = secondError.data?.error?.message || JSON.stringify(secondError.data);
                    throw new Error(`Imagen API Failed (Fallback): ${errorMessage}`);
                }
            } else {
                const errorMessage = firstError.data?.error?.message || JSON.stringify(firstError.data);
                throw new Error(`Imagen API Failed: ${errorMessage}`);
            }
        }

        if (data.predictions && data.predictions[0]?.bytesBase64Encoded) {
            const base64Image = `data:image/jpeg;base64,${data.predictions[0].bytesBase64Encoded}`;
            res.status(200).json({ image: base64Image });
        } else {
            throw new Error('No image generated by provider');
        }

    } catch (error) {
        console.error("Backend Generate Error:", error);
        // Security: Do not leak stack
        res.status(500).json({ error: error.message });
    }
}
