
import { GoogleGenerativeAI } from "@google/generative-ai";

export default async function handler(req, res) {
    if (req.method === 'OPTIONS') {
        res.status(200).end();
        return;
    }

    try {
        const apiKey = process.env.GOOGLE_GEMINI_API_KEY;
        if (!apiKey) {
            console.error('Server: Missing API Key');
            throw new Error('Configuration Error');
        }

        const { prompt, imageBase64 } = req.body;

        // --- SECURITY VALIDATION ---
        if (!prompt || typeof prompt !== 'string') {
            return res.status(400).json({ error: 'Invalid Prompt' });
        }

        if (prompt.length > 5000) {
            return res.status(400).json({ error: 'Prompt too long (Max 500 chars)' });
        }

        if (imageBase64) {
            // Approx check for crazy large payloads
            if (imageBase64.length > 15 * 1024 * 1024) { // ~11MB limit
                return res.status(413).json({ error: 'Reference Image too large' });
            }
        }
        // --- END VALIDATION ---

        // Use Imagen 4 Ultra via Google Generative Language API
        const url = `https://generativelanguage.googleapis.com/v1beta/models/imagen-3.0-generate-001:predict?key=${apiKey}`;

        const requestBody = {
            instances: [
                {
                    prompt: `Photorealistic industrial safety visualization, high quality, 4k: ${prompt}`,
                    image: imageBase64 ? { bytesBase64Encoded: imageBase64 } : undefined
                }
            ],
            parameters: {
                sampleCount: 1,
                aspectRatio: "4:3" // Match roughly typical photo aspect
            }
        };

        const response = await fetch(url, {
            method: 'POST',
            headers: {
                'Content-Type': 'application/json'
            },
            body: JSON.stringify(requestBody)
        });

        if (!response.ok) {
            // Log full error for admin, show generic to user
            const errorData = await response.json();
            console.error('Imagen API Error:', errorData);
            throw new Error('Image Generation Service Failed');
        }

        const data = await response.json();

        if (data.predictions && data.predictions[0]?.bytesBase64Encoded) {
            const base64Image = `data:image/jpeg;base64,${data.predictions[0].bytesBase64Encoded}`;
            res.status(200).json({ image: base64Image });
        } else {
            throw new Error('No image generated by provider');
        }

    } catch (error) {
        console.error("Backend Generate Error:", error);
        // Security: Do not leak stack
        res.status(500).json({ error: error.message });
    }
}
